export enum AuthErrorCode {
  TELEGRAM_AUTH_FAILED = 'TELEGRAM_AUTH_FAILED',
  INVALID_TELEGRAM_ID_TOKEN = 'INVALID_TELEGRAM_ID_TOKEN',
  TG_AUTH_EXPIRED = 'TG_AUTH_EXPIRED',
  INVALID_OAUTH_STATE = 'INVALID_OAUTH_STATE',
}
