export enum PostErrorCode {
  CREW_NOT_FOUND = 'CREW_NOT_FOUND',
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  ONLY_AUTHOR_CAN_EDIT_POST = 'ONLY_AUTHOR_CAN_EDIT_POST',
  ONLY_AUTHOR_OR_OWNER_CAN_DELETE_POST = 'ONLY_AUTHOR_OR_OWNER_CAN_DELETE_POST',
  ATTACHMENT_TOO_LARGE = 'ATTACHMENT_TOO_LARGE',
  MAX_ATTACHMENTS_EXCEEDED = 'MAX_ATTACHMENTS_EXCEEDED',
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
}
