export const CREW_LIMITS = {
  TITLE_MIN_LENGTH: 2,
  TITLE_MAX_LENGTH: 50,
  ALIAS_MAX_LENGTH: 20,
  MAX_MEMBERS_PER_CREW: 15,
  MAX_CREWS_PER_USER: 10,
  DEFAULT_CREWS_LIMIT: 5,
  MAX_CREWS_LIMIT: 15,
  DEFAULT_MEMBERS_LIMIT: 10,
  MAX_MEMBERS_LIMIT: 50,
} as const;
