export const POST_LIMITS = {
  CONTENT_MIN_LENGTH: 1,
  CONTENT_MAX_LENGTH: 1500,
  DEFAULT_PAGE_LIMIT: 20,
  MAX_PAGE_LIMIT: 50,
  MAX_ATTACHMENT_SIZE_BYTES: 200 * 1024 * 1024,
  MAX_ATTACHMENTS_PER_POST: 15,
} as const;
