export enum CrewErrorCode {
  CREW_NOT_FOUND = 'CREW_NOT_FOUND',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  ALREADY_MEMBER = 'ALREADY_MEMBER',
  CREW_IS_FULL = 'CREW_IS_FULL',
  USER_CREWS_LIMIT_REACHED = 'USER_CREWS_LIMIT_REACHED',
  ONLY_OWNER_CAN_DELETE_CREW = 'ONLY_OWNER_CAN_DELETE_CREW',
  ONLY_OWNER_CAN_UPDATE_CREW = 'ONLY_OWNER_CAN_UPDATE_CREW',
  ONLY_OWNER_CAN_KICK_MEMBERS = 'ONLY_OWNER_CAN_KICK_MEMBERS',
  CANNOT_EDIT_OTHER_MEMBER_ALIAS = 'CANNOT_EDIT_OTHER_MEMBER_ALIAS',
  CANNOT_LEAVE_AS_OWNER = 'CANNOT_LEAVE_AS_OWNER',
}
