export const SPLIT_LIMITS = {
  TITLE_MIN_LENGTH: 2,
  TITLE_MAX_LENGTH: 30,
  DESC_MIN_LENGTH: 1,
  DESC_MAX_LENGTH: 1000,
  MSG_MIN_LENGTH: 1,
  MSG_MAX_LENGTH: 50,
  MIN_EXPENSES: 1,
  MAX_EXPENSES: 10,
  MIN_MEMBERS_PER_EXPENSE: 2,
  DEFAULT_PAGE_LIMIT: 10,
  MAX_PAGE_LIMIT: 50,
} as const;
